apiVersion: v2
appVersion: 2.1.2
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.helm.sh/stable
  version: 8.6.4
- condition: redis.enabled
  name: redis
  repository: https://charts.helm.sh/stable
  version: 10.5.7
description: Airflow Helm Chart (User Community) - used to deploy Apache Airflow on
  Kubernetes
home: https://github.com/airflow-helm/charts
icon: https://airflow.apache.org/_images/pin_large.png
keywords:
- airflow
- dag
- workflow
maintainers:
- name: thesuperzapper
  url: https://github.com/thesuperzapper
- name: gsemet
  url: https://github.com/gsemet
name: airflow
sources:
- https://github.com/airflow-helm/charts/tree/main/charts/airflow
version: 8.5.2
